<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework Condition=" '$(OS)' == 'Windows_NT' ">net9.0-windows10.0.19041.0</TargetFramework>
    <TargetFramework Condition=" '$(OS)' != 'Windows_NT' ">net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>InterlinedSync.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="RichardSzalay.MockHttp" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterlinedSync\InterlinedSync.csproj" />
  </ItemGroup>

  <ItemGroup Condition=" '$(OS)' != 'Windows_NT' ">
    <Compile Remove="SystemTray\TrayMenuBuilderTests.cs" />
  </ItemGroup>

</Project>
